[2025-04-22T19:28:35.040-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T19:28:35.045-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T23:28:31.175549+00:00 [queued]>
[2025-04-22T19:28:35.049-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T23:28:31.175549+00:00 [queued]>
[2025-04-22T19:28:35.049-0400] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-22T19:28:35.056-0400] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_notebook> on 2025-04-22 23:28:31.175549+00:00
[2025-04-22T19:28:35.058-0400] {standard_task_runner.py:72} INFO - Started process 7305 to run task
[2025-04-22T19:28:35.061-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fashion_data_pipeline', 'execute_notebook', 'manual__2025-04-22T23:28:31.175549+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/FashionData_DAG.py', '--cfg-path', '/tmp/tmp4t6rast4']
[2025-04-22T19:28:35.061-0400] {standard_task_runner.py:105} INFO - Job 67: Subtask execute_notebook
[2025-04-22T19:28:35.090-0400] {task_command.py:467} INFO - Running <TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T23:28:31.175549+00:00 [running]> on host BOOK-KTS1KMKSNJ.
[2025-04-22T19:28:35.132-0400] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fashion_data_pipeline' AIRFLOW_CTX_TASK_ID='execute_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:28:31.175549+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:28:31.175549+00:00'
[2025-04-22T19:28:35.133-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T19:28:35.133-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T19:28:35.134-0400] {logging_mixin.py:190} INFO - Current task name:execute_notebook state:running start_date:2025-04-22 23:28:35.046177+00:00
[2025-04-22T19:28:35.134-0400] {logging_mixin.py:190} INFO - Dag name:fashion_data_pipeline and current dag run status:running
[2025-04-22T19:28:35.134-0400] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T19:28:35.135-0400] {FashionData_DAG.py:58} INFO - Executing notebook: /home/megin_mathew/airflow/notebooks/Fashion_Data_Pipeline.ipynb
[2025-04-22T19:28:35.135-0400] {FashionData_DAG.py:59} INFO - Output will be saved to: /home/megin_mathew/airflow/notebook_outputs/Fashion_Data_Pipeline-output-2025-04-22.ipynb
[2025-04-22T19:28:35.135-0400] {FashionData_DAG.py:60} INFO - Parameters passed to notebook: {'execution_date': '2025-04-22T23:28:31.175549+00:00', 'dag_run_id': 'manual__2025-04-22T23:28:31.175549+00:00', 'ds': '2025-04-22', 'ds_nodash': '20250422'}
[2025-04-22T19:28:35.135-0400] {execute.py:83} INFO - Input Notebook:  /home/megin_mathew/airflow/notebooks/Fashion_Data_Pipeline.ipynb
[2025-04-22T19:28:35.135-0400] {execute.py:84} INFO - Output Notebook: /home/megin_mathew/airflow/notebook_outputs/Fashion_Data_Pipeline-output-2025-04-22.ipynb
[2025-04-22T19:28:36.149-0400] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2025-04-22T19:28:36.150-0400] {engines.py:223} INFO - Executing Cell 1---------------------------------------
[2025-04-22T19:28:36.166-0400] {engines.py:261} INFO - Ending Cell 1------------------------------------------
[2025-04-22T19:28:36.172-0400] {engines.py:223} INFO - Executing Cell 2---------------------------------------
[2025-04-22T19:28:36.178-0400] {engines.py:261} INFO - Ending Cell 2------------------------------------------
[2025-04-22T19:28:36.179-0400] {engines.py:223} INFO - Executing Cell 3---------------------------------------
[2025-04-22T19:28:36.596-0400] {clientwrap.py:91} INFO - Requirement already satisfied: kagglehub in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (0.3.11)
Requirement already satisfied: pandas in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: psycopg2-binary in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (1.4.54)
Requirement already satisfied: packaging in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: numpy>=1.26.0 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from sqlalchemy) (3.2.0)
Requirement already satisfied: six>=1.5 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (2025.1.31)

[2025-04-22T19:28:36.935-0400] {engines.py:261} INFO - Ending Cell 3------------------------------------------
[2025-04-22T19:28:36.937-0400] {engines.py:223} INFO - Executing Cell 4---------------------------------------
[2025-04-22T19:28:37.013-0400] {clientwrap.py:91} INFO - ['KaggleDatasetAdapter', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'auth', 'cache', 'clients', 'colab_cache_resolver', 'competition', 'competition_download', 'config', 'dataset_download', 'dataset_load', 'dataset_upload', 'datasets', 'datasets_enums', 'datasets_helpers', 'env', 'exceptions', 'gcs_upload', 'get_package_asset_path', 'handle', 'http_resolver', 'integrity', 'kaggle_cache_resolver', 'kagglehub', 'load_dataset', 'logger', 'login', 'model_download', 'model_upload', 'models', 'models_helpers', 'notebook_output_download', 'notebooks', 'package_import', 'packages', 'registry', 'resolver', 'signing', 'tracker', 'utility_script_install', 'utility_scripts', 'whoami']

[2025-04-22T19:28:37.013-0400] {clientwrap.py:98} WARNING - /home/megin_mathew/airflow_venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[2025-04-22T19:28:37.014-0400] {engines.py:261} INFO - Ending Cell 4------------------------------------------
[2025-04-22T19:28:37.015-0400] {engines.py:223} INFO - Executing Cell 5---------------------------------------
[2025-04-22T19:28:37.479-0400] {clientwrap.py:91} INFO - Requirement already satisfied: kaggle in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (1.7.4.2)
Requirement already satisfied: bleach in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (79.0.0)
Requirement already satisfied: six>=1.10 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /home/megin_mathew/airflow_venv/lib/python3.12/site-packages (from kaggle) (0.5.1)

[2025-04-22T19:28:37.841-0400] {clientwrap.py:91} INFO - Note: you may need to restart the kernel to use updated packages.

[2025-04-22T19:28:37.845-0400] {engines.py:261} INFO - Ending Cell 5------------------------------------------
[2025-04-22T19:28:37.848-0400] {engines.py:223} INFO - Executing Cell 6---------------------------------------
[2025-04-22T19:28:37.925-0400] {clientwrap.py:91} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/megin_mathew/.config/kaggle/kaggle.json'
Kaggle module is successfully installed!

[2025-04-22T19:28:37.927-0400] {engines.py:261} INFO - Ending Cell 6------------------------------------------
[2025-04-22T19:28:37.929-0400] {engines.py:223} INFO - Executing Cell 7---------------------------------------
[2025-04-22T19:28:37.934-0400] {clientwrap.py:91} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/megin_mathew/.config/kaggle/kaggle.json'
Kaggle API authentication successful!

[2025-04-22T19:28:37.936-0400] {engines.py:261} INFO - Ending Cell 7------------------------------------------
[2025-04-22T19:28:37.938-0400] {engines.py:223} INFO - Executing Cell 8---------------------------------------
[2025-04-22T19:29:27.499-0400] {clientwrap.py:91} INFO - Downloaded: transactions.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:31.433-0400] {clientwrap.py:98} WARNING - /home/megin_mathew/airflow_venv/lib/python3.12/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

[2025-04-22T19:29:35.873-0400] {clientwrap.py:91} INFO - Downloaded: customers.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:36.445-0400] {clientwrap.py:91} INFO - Downloaded: discounts.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:36.806-0400] {clientwrap.py:91} INFO - Downloaded: employees.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:37.305-0400] {clientwrap.py:91} INFO - Downloaded: products.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:37.419-0400] {clientwrap.py:91} INFO - Downloaded: stores.csv → Stored in: /home/megin_mathew/fashion_dataset

[2025-04-22T19:29:37.424-0400] {engines.py:261} INFO - Ending Cell 8------------------------------------------
[2025-04-22T19:29:37.430-0400] {engines.py:223} INFO - Executing Cell 9---------------------------------------
[2025-04-22T19:29:37.444-0400] {engines.py:261} INFO - Ending Cell 9------------------------------------------
[2025-04-22T19:29:37.446-0400] {engines.py:223} INFO - Executing Cell 10--------------------------------------
[2025-04-22T19:29:37.449-0400] {engines.py:261} INFO - Ending Cell 10-----------------------------------------
[2025-04-22T19:29:37.451-0400] {engines.py:223} INFO - Executing Cell 11--------------------------------------
[2025-04-22T19:29:39.355-0400] {clientwrap.py:98} WARNING - 25/04/22 19:29:39 WARN Utils: Your hostname, BOOK-KTS1KMKSNJ resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
25/04/22 19:29:39 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

[2025-04-22T19:29:39.633-0400] {clientwrap.py:98} WARNING - Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/22 19:29:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
25/04/22 19:29:39 WARN SparkConf: Note that spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone/kubernetes and LOCAL_DIRS in YARN).

[2025-04-22T19:29:40.627-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,626 - INFO - Starting data load process...

[2025-04-22T19:29:40.736-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,734 - WARNING - File not found: C:/Users/megin/fashion_dataset/stores.csv

[2025-04-22T19:29:40.737-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,735 - WARNING - File not found: C:/Users/megin/fashion_dataset/employees.csv

[2025-04-22T19:29:40.738-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,736 - WARNING - File not found: C:/Users/megin/fashion_dataset/products.csv

[2025-04-22T19:29:40.738-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,736 - WARNING - File not found: C:/Users/megin/fashion_dataset/discounts.csv

[2025-04-22T19:29:40.739-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,736 - WARNING - File not found: C:/Users/megin/fashion_dataset/customers.csv

[2025-04-22T19:29:40.739-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,737 - WARNING - File not found: C:/Users/megin/fashion_dataset/transactions.csv

[2025-04-22T19:29:40.740-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:40,737 - INFO - Data load completed successfully

[2025-04-22T19:29:41.002-0400] {clientwrap.py:98} WARNING - 2025-04-22 19:29:41,001 - INFO - Process completed in 0:00:00.373906

[2025-04-22T19:29:41.006-0400] {engines.py:261} INFO - Ending Cell 11-----------------------------------------
[2025-04-22T19:29:41.009-0400] {engines.py:223} INFO - Executing Cell 12--------------------------------------
[2025-04-22T19:29:41.011-0400] {engines.py:261} INFO - Ending Cell 12-----------------------------------------
[2025-04-22T19:29:43.650-0400] {FashionData_DAG.py:79} INFO - Notebook execution completed successfully
[2025-04-22T19:29:43.652-0400] {python.py:240} INFO - Done. Returned value was: True
[2025-04-22T19:29:43.736-0400] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T19:29:43.738-0400] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fashion_data_pipeline, task_id=execute_notebook, run_id=manual__2025-04-22T23:28:31.175549+00:00, execution_date=20250422T232831, start_date=20250422T232835, end_date=20250422T232943
[2025-04-22T19:29:43.770-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-22T19:29:43.770-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-22T19:29:43.771-0400] {logging_mixin.py:190} INFO - Dag name:fashion_data_pipeline queued_at:2025-04-22 23:28:31.194007+00:00
[2025-04-22T19:29:43.771-0400] {logging_mixin.py:190} INFO - Task hostname:BOOK-KTS1KMKSNJ. operator:PythonOperator
[2025-04-22T19:29:43.793-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T19:29:43.831-0400] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T19:29:43.832-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
